name: CHESS CD
env: 
  AWS_REGION   : "eu-central-1"
  NODE_VERSION : "6.x"
on:
  
  push:
    branches: 
      - feature/cd

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Setup node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Gazer dependencies
      run: npm install --production
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.2.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Build frontend application 
      run: |
        NODE_ENV=production API_URL=//$(aws ec2 describe-instances \
        --region ${{ env.AWS_REGION }} \
        --filter Name=tag:Name,Values=chess-back \
        --output=text |grep ASSOCIATION|uniq -c|awk '{print $5}'):8081 \
        npm run build
    
    - name: Zip artifacts
      run: |
       zip ansible/backend -r node_modules/ lib/server/ lib/common/
       cd lib/client
       zip ../../ansible/frontend -r ./*
       ls -l
       
    - name: Import key
      run: 'echo "$SSH_KEY" > ./ansible/key'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Prepare ansible to work
      run: |
        pip install boto
        pip install ansible
        cd ./ansible
        chmod +x  ec2.py
        chmod 600 key
      
     
