name: CHESS APP CI

on:
#   pull_request:
#     branches: 
#       - master
  push:
    branches: 
      - feauture/ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Clone our repo 
      uses: actions/checkout@v2
      
    - name: Setup node.js 6.x
      uses: actions/setup-node@v1
      with:
        node-version: 6.x
        
    - name: Gazer dependencies
      run: npm install
      
    - name: Test app
      run: npm test 

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
    - name: Status message to Telegram
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.TG_USER }}
        token: ${{ secrets.TG_TOKEN }}
        status: ${{ job.status }}
