# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CHESS APP CI

on:
#   pull_request:
#     branches: 
#       - master
  push:
    branches: 
      - feauture/ci

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:  
    - name: Clone our repo 
      uses: actions/checkout@v2
      
    - name: Pick Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Gazer dependencies, build code
      run: npm install
      
    - name: Test app
      run: npm test 
      
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
